-- À exécuter dans Supabase : SQL Editor → New query → Coller → Run
-- Prestations (coupes/services) : le coiffeur ajoute ses prestations (photo optionnelle, intitulé, prix €, prix points).
-- Les réservations peuvent être liées à une prestation.

-- 1) Table prestations
CREATE TABLE IF NOT EXISTS prestations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barber_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  image_url text,
  price_eur numeric(10,2) NOT NULL DEFAULT 0,
  price_points int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT prestation_price_eur_non_neg CHECK (price_eur >= 0),
  CONSTRAINT prestation_price_points_non_neg CHECK (price_points >= 0)
);

ALTER TABLE prestations ENABLE ROW LEVEL SECURITY;

-- Le coiffeur peut tout faire sur ses prestations
DROP POLICY IF EXISTS "Barbers can manage own prestations" ON prestations;
CREATE POLICY "Barbers can manage own prestations"
ON prestations FOR ALL TO authenticated
USING (barber_id = auth.uid())
WITH CHECK (barber_id = auth.uid());

-- Les clients (et tous les connectés) peuvent lire les prestations pour réserver
DROP POLICY IF EXISTS "Authenticated can read prestations" ON prestations;
CREATE POLICY "Authenticated can read prestations"
ON prestations FOR SELECT TO authenticated
USING (true);

-- 2) Colonne prestation_id sur bookings (nullable pour anciennes résas)
ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS prestation_id bigint REFERENCES prestations(id) ON DELETE SET NULL;

-- 3) Bucket storage pour les photos des prestations (optionnel)
INSERT INTO storage.buckets (id, name, public)
VALUES ('prestations', 'prestations', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Les coiffeurs peuvent uploader dans leur dossier (prestations/{barber_id}/...)
DROP POLICY IF EXISTS "Barbers can upload prestation images" ON storage.objects;
CREATE POLICY "Barbers can upload prestation images"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'prestations'
  AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Lecture publique des images prestations
DROP POLICY IF EXISTS "Public read prestations bucket" ON storage.objects;
CREATE POLICY "Public read prestations bucket"
ON storage.objects FOR SELECT TO public
USING (bucket_id = 'prestations');

-- 4) RLS profiles : les clients doivent pouvoir lire les barbers (nom, prénom) pour la réservation
-- À exécuter si la table profiles a déjà des policies (pas de conflit avec "Barbers can read profiles")
DROP POLICY IF EXISTS "Authenticated can read barber profiles for booking" ON profiles;
CREATE POLICY "Authenticated can read barber profiles for booking"
ON profiles FOR SELECT TO authenticated
USING (role = 'barber');
