-- À exécuter dans Supabase : SQL Editor → New query → Coller → Run
-- Notifications client : nouveau produit shop, points ajoutés, rappel RDV 24h avant.

-- 1) Table des notifications
CREATE TABLE IF NOT EXISTS notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type text NOT NULL,
  title text NOT NULL,
  body text,
  payload jsonb DEFAULT '{}',
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications (user_id, read_at);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications (user_id, created_at DESC);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Le client peut lire et mettre à jour (marquer lu) ses propres notifications
DROP POLICY IF EXISTS "Users can read own notifications" ON notifications;
CREATE POLICY "Users can read own notifications"
ON notifications FOR SELECT TO authenticated
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can update own notifications" ON notifications;
CREATE POLICY "Users can update own notifications"
ON notifications FOR UPDATE TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- Le client peut créer une notif pour lui (rappel RDV 24h créé côté client)
DROP POLICY IF EXISTS "Users can insert own notifications" ON notifications;
CREATE POLICY "Users can insert own notifications"
ON notifications FOR INSERT TO authenticated
WITH CHECK (user_id = auth.uid());

-- 2) Trigger : nouveau produit au shop → notif pour tous les clients
CREATE OR REPLACE FUNCTION public.notify_new_shop_item()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.notifications (user_id, type, title, body, payload)
  SELECT p.id, 'new_shop_item', 'Nouveau au shop', 'Un nouveau produit est disponible.', jsonb_build_object('shop_item_id', new.id)
  FROM public.profiles p
  WHERE p.role = 'client';
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_shop_item_created_notify ON shop_items;
CREATE TRIGGER on_shop_item_created_notify
  AFTER INSERT ON shop_items
  FOR EACH ROW
  EXECUTE PROCEDURE public.notify_new_shop_item();

-- 3) Trigger : points ajoutés → notif pour le client concerné
CREATE OR REPLACE FUNCTION public.notify_points_added()
RETURNS trigger AS $$
DECLARE
  v_user_id uuid;
BEGIN
  IF (new.points IS NULL OR new.points <= 0) THEN
    RETURN new;
  END IF;
  SELECT c.user_id INTO v_user_id FROM public.customers c WHERE c.id = new.customer_id LIMIT 1;
  IF v_user_id IS NOT NULL THEN
    INSERT INTO public.notifications (user_id, type, title, body, payload)
    VALUES (v_user_id, 'points_added', 'Points ajoutés', 'Tu as reçu ' || new.points || ' points.', jsonb_build_object('points', new.points, 'transaction_id', new.id));
  END IF;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_transaction_points_notify ON transactions;
CREATE TRIGGER on_transaction_points_notify
  AFTER INSERT ON transactions
  FOR EACH ROW
  EXECUTE PROCEDURE public.notify_points_added();
