-- À exécuter dans Supabase : SQL Editor → New query → Coller → Run
-- Feed d'actualités : le coiffeur publie des posts (texte, image, vocal), les clients les voient sur l'accueil.

-- 1) Table des actualités (texte optionnel + image et/ou vocal optionnels)
CREATE TABLE IF NOT EXISTS feed_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content text NOT NULL DEFAULT '',
  image_url text,
  audio_url text,
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Colonnes image/vocal si la table existait déjà
ALTER TABLE feed_posts ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE feed_posts ADD COLUMN IF NOT EXISTS audio_url text;

-- 2) RLS
ALTER TABLE feed_posts ENABLE ROW LEVEL SECURITY;

-- Tout utilisateur connecté peut lire les posts
DROP POLICY IF EXISTS "Anyone authenticated can read feed" ON feed_posts;
CREATE POLICY "Anyone authenticated can read feed"
ON feed_posts FOR SELECT TO authenticated
USING (true);

-- Seuls les coiffeurs peuvent insérer
DROP POLICY IF EXISTS "Barbers can insert feed posts" ON feed_posts;
CREATE POLICY "Barbers can insert feed posts"
ON feed_posts FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'barber')
);

-- L'auteur (coiffeur) peut modifier/supprimer ses posts
DROP POLICY IF EXISTS "Authors can update own feed post" ON feed_posts;
CREATE POLICY "Authors can update own feed post"
ON feed_posts FOR UPDATE TO authenticated
USING (created_by = auth.uid())
WITH CHECK (created_by = auth.uid());

DROP POLICY IF EXISTS "Authors can delete own feed post" ON feed_posts;
CREATE POLICY "Authors can delete own feed post"
ON feed_posts FOR DELETE TO authenticated
USING (created_by = auth.uid());

-- 3) Bucket pour médias des actualités (images + vocaux)
INSERT INTO storage.buckets (id, name, public)
VALUES ('feed-media', 'feed-media', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Seuls les coiffeurs peuvent uploader
DROP POLICY IF EXISTS "Barbers can upload feed media" ON storage.objects;
CREATE POLICY "Barbers can upload feed media"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'feed-media'
  AND EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'barber')
);

-- Lecture publique pour affichage côté client
DROP POLICY IF EXISTS "Public read feed media" ON storage.objects;
CREATE POLICY "Public read feed media"
ON storage.objects FOR SELECT TO public
USING (bucket_id = 'feed-media');
