-- À exécuter dans Supabase : SQL Editor → New query → Coller → Run
-- Objets du shop : le coiffeur crée des articles (intitulé, description, points) ; les clients les achètent avec leurs points.
-- "Coupe gratuite" est un objet comme les autres (avec is_coupe_offerte = true pour la règle "une seule en attente").

-- 1) Table des objets du shop
CREATE TABLE IF NOT EXISTS shop_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  points int NOT NULL CHECK (points > 0),
  is_coupe_offerte boolean NOT NULL DEFAULT false,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE shop_items ENABLE ROW LEVEL SECURITY;

-- Tout le monde connecté peut lire les objets
DROP POLICY IF EXISTS "Anyone can read shop items" ON shop_items;
CREATE POLICY "Anyone can read shop items"
ON shop_items FOR SELECT TO authenticated USING (true);

-- Seuls les coiffeurs peuvent créer / modifier / supprimer
DROP POLICY IF EXISTS "Barbers can insert shop items" ON shop_items;
CREATE POLICY "Barbers can insert shop items"
ON shop_items FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'barber'));

DROP POLICY IF EXISTS "Barbers can update shop items" ON shop_items;
CREATE POLICY "Barbers can update shop items"
ON shop_items FOR UPDATE TO authenticated
USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'barber'))
WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'barber'));

DROP POLICY IF EXISTS "Barbers can delete shop items" ON shop_items;
CREATE POLICY "Barbers can delete shop items"
ON shop_items FOR DELETE TO authenticated
USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'barber'));

-- 2) Lier les achats aux objets (transactions)
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS shop_item_id bigint REFERENCES shop_items(id) ON DELETE SET NULL;

-- 3) Objet par défaut : Coupe gratuite (à insérer une seule fois)
INSERT INTO shop_items (title, description, points, is_coupe_offerte)
SELECT 'Coupe gratuite', 'Une coupe offerte à utiliser chez le coiffeur.', 100, true
WHERE NOT EXISTS (SELECT 1 FROM shop_items WHERE is_coupe_offerte = true);
