-- À exécuter dans Supabase : SQL Editor → New query → Coller → Run
-- Annulations de réservations par le coiffeur : motif enregistré et visible par le client.

-- 1) Table des annulations (après suppression de la réservation)
CREATE TABLE IF NOT EXISTS booking_cancellations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot_id bigint NOT NULL REFERENCES availability_slots(id) ON DELETE CASCADE,
  customer_id uuid NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  cancelled_at timestamptz NOT NULL DEFAULT now(),
  cancel_reason text,
  cancelled_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE
);

ALTER TABLE booking_cancellations ENABLE ROW LEVEL SECURITY;

-- Le coiffeur peut insérer une annulation (lorsqu'il annule une résa)
DROP POLICY IF EXISTS "Barbers can insert cancellations" ON booking_cancellations;
CREATE POLICY "Barbers can insert cancellations"
ON booking_cancellations FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'barber')
);

-- Le client peut lire les annulations qui le concernent
DROP POLICY IF EXISTS "Clients can read own cancellations" ON booking_cancellations;
CREATE POLICY "Clients can read own cancellations"
ON booking_cancellations FOR SELECT TO authenticated
USING (
  customer_id IN (SELECT id FROM customers WHERE user_id = auth.uid())
);

-- Le coiffeur peut lire les annulations (pour ses créneaux)
DROP POLICY IF EXISTS "Barbers can read cancellations" ON booking_cancellations;
CREATE POLICY "Barbers can read cancellations"
ON booking_cancellations FOR SELECT TO authenticated
USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'barber')
);

-- 2) Le coiffeur peut supprimer une réservation (pour annuler un RDV)
DROP POLICY IF EXISTS "Barbers can delete bookings for own slots" ON bookings;
CREATE POLICY "Barbers can delete bookings for own slots"
ON bookings FOR DELETE TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM availability_slots a
    WHERE a.id = bookings.slot_id AND a.created_by = auth.uid()
  )
);
