-- À exécuter dans Supabase : SQL Editor → New query → Coller → Run
-- Réservation : le coiffeur crée des créneaux (date, heure début, heure fin), le client réserve et peut annuler.
-- Si tu as déjà exécuté ce script et eu une erreur sur bookings_customer_id_fkey, exécute d'abord : DROP TABLE IF EXISTS bookings;

-- 1) Créneaux créés par le coiffeur
CREATE TABLE IF NOT EXISTS availability_slots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot_date date NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT slot_times_check CHECK (start_time < end_time)
);

ALTER TABLE availability_slots ENABLE ROW LEVEL SECURITY;

-- Les coiffeurs peuvent tout faire sur les créneaux
DROP POLICY IF EXISTS "Barbers can manage slots" ON availability_slots;
CREATE POLICY "Barbers can manage slots"
ON availability_slots FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'barber'))
WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'barber'));

-- Les clients peuvent lire les créneaux (pour voir les dispos)
DROP POLICY IF EXISTS "Clients can read slots" ON availability_slots;
CREATE POLICY "Clients can read slots"
ON availability_slots FOR SELECT TO authenticated
USING (true);

-- 2) Réservations (un créneau = une résa max)
-- Si ta table customers a id en uuid, on utilise uuid pour customer_id
CREATE TABLE IF NOT EXISTS bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot_id bigint NOT NULL REFERENCES availability_slots(id) ON DELETE CASCADE,
  customer_id uuid NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(slot_id)
);

ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Le client peut réserver (insert) si customer_id = son customer
DROP POLICY IF EXISTS "Clients can book own" ON bookings;
CREATE POLICY "Clients can book own"
ON bookings FOR INSERT TO authenticated
WITH CHECK (
  customer_id IN (SELECT id FROM customers WHERE user_id = auth.uid())
);

-- Le client peut annuler (delete) sa propre résa
DROP POLICY IF EXISTS "Clients can cancel own booking" ON bookings;
CREATE POLICY "Clients can cancel own booking"
ON bookings FOR DELETE TO authenticated
USING (
  customer_id IN (SELECT id FROM customers WHERE user_id = auth.uid())
);

-- Le client peut lire ses résas
DROP POLICY IF EXISTS "Clients can read own bookings" ON bookings;
CREATE POLICY "Clients can read own bookings"
ON bookings FOR SELECT TO authenticated
USING (
  customer_id IN (SELECT id FROM customers WHERE user_id = auth.uid())
);

-- Le coiffeur peut tout lire
DROP POLICY IF EXISTS "Barbers can read bookings" ON bookings;
CREATE POLICY "Barbers can read bookings"
ON bookings FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'barber'));
