-- À exécuter dans Supabase : SQL Editor -> Run
-- Permet au coiffeur de marquer un rendez-vous comme "venu" ou "absent"
-- et d'éviter de traiter plusieurs fois le même booking.

CREATE TABLE IF NOT EXISTS booking_outcomes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id bigint NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE,
  slot_id bigint NOT NULL REFERENCES availability_slots(id) ON DELETE CASCADE,
  customer_id uuid NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  barber_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  prestation_points int NOT NULL DEFAULT 0,
  status text NOT NULL CHECK (status IN ('arrived', 'no_show')),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE booking_outcomes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Barbers can insert booking outcomes" ON booking_outcomes;
CREATE POLICY "Barbers can insert booking outcomes"
ON booking_outcomes FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'barber')
);

DROP POLICY IF EXISTS "Barbers can read booking outcomes" ON booking_outcomes;
CREATE POLICY "Barbers can read booking outcomes"
ON booking_outcomes FOR SELECT TO authenticated
USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'barber')
);
